Server/RailsServer/config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  match '/collect' => 'posts#collect', via: :post#, as: 'collect'
  match '/testpost' => 'posts#testpost', via: :get#, as: 'login'

  match '/modifyStatus' => 'posts#modifyStatus', via: :post
  match '/modifyStatusAgain' => 'posts#modifyStatusAgain', via: :post
  match '/getPickUpList' => 'posts#getPickUpList', via: :post

  resources :users
  post 'login', to: 'users#login'
  get 'confirms', to: 'posts#confirms'

  resources :posts do
    member do
      get 'confirm'
    end
  end

  namespace :api do
    resources :posts, defaults: { format: 'json' }
  end

end

Server/RailsServer/app/models/org.rb
class Org < ActiveRecord::Base
  #attr_accessible :name deprecation

end

Server/RailsServer/app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, PictureUploader
end

Server/RailsServer/app/models/user.rb
class User < ActiveRecord::Base
end

Server/RailsServer/app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController

  def index
    #@posts = Post.all
	    
	@posts = Post.where(status: 0).find_each

    respond_to do |format|
      format.json { render :json => @posts }
    end
  end
end

Server/RailsServer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :null_session
  protect_from_forgery with: :exception
end

Server/RailsServer/app/controllers/posts_controller.rb
require 'json'

class PostsController < ApplicationController

  protect_from_forgery :secret => 'any_phrase', :except => :collect,:except => :modifyStatus,:except => :getPickUpList, :except => :modifyStatusAgain

  def confirm
    redirect_to :confirms
  end

  def confirms
    @posts = Post.all
  end

	def index
    @posts = Post.all
	end

  def show
    @post = Post.find(params[:id])
  end

  def collect
   puts request.headers

    username = request.headers["Username"]
    password = request.headers["Password"]

    users = User.all
    user_id = 'None'
    
    users.each do |user|
      if user.email == username && user.password == password
        if user.user_type == 'Charity'
          user_id = user.id.to_s
        end
      end
    end

    render text: user_id
  end

  def getPickUpList
    puts request.headers
    charity = request.headers["Charity"]
    newposts = Post.where(status: 1).where(org: charity).find_each

    respond_to do |format|
      format.json { render :json => newposts }
    end

  end

  def modifyStatus
    puts request.headers
    item = request.headers["Name"]
    provider = request.headers["Provider"]
    charity = request.headers["Charity"]

    posts = Post.all

    posts.each do |post|
      if post.item == item && post.super == provider
        post.org = charity
        post.status = 1
        post.save
      end
    end

    newposts = Post.where(status: 0).find_each

    respond_to do |format|
      format.json { render :json => newposts }
    end
  end

  def modifyStatusAgain
    puts request.headers
    item = request.headers["Name"]
    provider = request.headers["Provider"]
    charity = request.headers["Charity"]

    posts = Post.all

    posts.each do |post|
      if post.item == item && post.super == provider && post.org == charity
        post.status = 2
        post.save
      end
    end

    newposts = Post.where(status: 1).where(org: charity).find_each

    respond_to do |format|
      format.json { render :json => newposts }
    end

  end

  def new
    @post = Post.new
  end

  def create
    available_time_start = DateTime.new(params[:post]["available_time_start(1i)"].to_i, params[:post]["available_time_start(2i)"].to_i, params[:post]["available_time_start(3i)"].to_i, params[:post]["available_time_start(4i)"].to_i, params[:post]["available_time_start(5i)"].to_i)
    available_time_end = DateTime.new(params[:post]["available_time_end(1i)"].to_i, params[:post]["available_time_end(2i)"].to_i, params[:post]["available_time_end(3i)"].to_i, params[:post]["available_time_end(4i)"].to_i, params[:post]["available_time_end(5i)"].to_i)

    @currUser = UsersHelper.current_user

    @post = Post.new(post_params)
    @post.update(status: 0)
    @post.update(super: @currUser.name)
    @post.update(available_time_start: available_time_start)
    @post.update(available_time_end: available_time_end)

    # Upload image
    @post.image = params[:file]

    #@post.image.url # => '/url/to/file.png'
    #@post.image.current_path # => 'path/to/file.png'
    #@post.image.identifier # => 'file.png'

    if @post.save
      redirect_to posts_path#, :notice => 'Successfully uploaded'
    else
      render "new"
    end
  end

  def uploadImage post
    require 'carrierwave/orm/activerecord'

    uploader = PictureUploader.new
    uploader.store!(my_file)

    u = User.new(params[:user])
    u.save!
    u.image.url # => '/url/to/file.png'
    u.image.current_path # => 'path/to/file.png'
    u.image.identifier # => 'file.png'

    #uploader.retrieve_from_store!('my_file.png')
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:item, :description, :quantity, :loc, :expir, :image)
  end
end

Server/RailsServer/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  def login
    @check_user = User.new(user_params)
    @users = User.all
    @jump = 0
    @users.each do |user|
      if user.email == @check_user.email
        if user.password == @check_user.password
          UsersHelper.setCurr user

          if user.user_type == "Doner"
            @jump = 1
          else
            @jump = 2
          end
        end
      end
    end
    respond_to do |format|
      if @jump == 0
       format.html { redirect_to users_url, notice: 'Username or Password is not matched.'}
      elsif @jump == 1 # when user is donater
       format.html { redirect_to posts_url}
      elsif @jump == 2 #when user is collecter
       format.html {redirect_to user}
      end
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :location, :user_type, :email)
    end
end

Server/RailsServer/app/helpers/application_helper.rb
module ApplicationHelper
end

Server/RailsServer/app/helpers/posts_helper.rb
module PostsHelper
end

Server/RailsServer/app/helpers/users_helper.rb
module UsersHelper

  def self.setCurr current_user
    @current_user = current_user
  end

  def self.current_user
    @current_user
  end

end

Server/RailsServer/app/views/layouts/_footer.html.erb
<footer class="footer center">
	<!-- <p>The ServiceMonitoring System by Service Monitoring Orange</p> -->
</footer>

Server/RailsServer/app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
     <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Go Get It!!!</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <nav>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Donates', posts_path %></li>
          <li><%= link_to 'Confirmations', confirms_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/">Home</a></li>
          <%# <% if user_signed_in? %>
               <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Signed in as
                    Donator
                <span class="caret"></span></a>
                 <ul class="dropdown-menu">
                    <li><%= link_to 'Log out', '/sign_out', method: :delete %></li>
                  </ul>
                </li>
          <%# <% else %>
          <%#     <li><%= link_to 'Log in', '/sign_in' %></li>
          <%# <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

Server/RailsServer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>RailsServer</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="page-wrapper">
            <%= render 'layouts/header' %>


            <div class="container-fluid content">
                </br>
                </br>
                    <%= yield %>
            </div>

            <%= render 'layouts/footer' %>
        </div>

    </body>
</html>

Server/RailsServer/app/views/posts/_form.html.erb
<%= form_for(@post, html: { id: "post_form" }) do |f| %>
  <div class="field">
      <label>Foods</label>
    <%= f.text_field :item, :required => true, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :descritpion %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :Location %><br>
    <%= f.text_field :loc, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :available_time_start %><br>
    <%= f.datetime_select :available_time_start, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :available_time_end %><br>
    <%= f.datetime_select :available_time_end, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label 'Expire date' %><br>
    <%= f.date_field :expir, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label 'Expire date' %><br>
    <%= f.file_field :image, multiple: false %>
  </div>
  <div class="actions">
      <%= f.submit "Submit" , class:"btn btn-success "%>
    <button type="reset" class="btn btn-default">Reset</button>
  </div>
<% end %>

Server/RailsServer/app/views/posts/confirms.html.erb
<div class="panel panel-default">
    <div class="panel-heading" align="center"><h2><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><br>Confirmed List</h2></div>
    <!-- /.panel-heading -->
    <div class="panel-body">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Quantity(kg)</th>
                        <th>Organization</th>
                        <th>Pick Up Time</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @posts.each do |post| %>
                        <tr class="odd gradeX">
                            <td><%= link_to post.item, post, :class =>"btn btn-info btn-sm white-font survey-btn"%></td>
                            <td><%= post.quantity %></td>
                            <td><%= post.org %></td>
                            <td><%= post.picktime.to_formatted_s(:db) %></td>
                            <td>
                                <%= link_to 'Finish', confirm_post_path(post), :class =>"btn btn-warning btn-sm white-font survey-btn" %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
    </div>
    <!-- /.panel-body -->
</div>
<script>
$(document).ready(function() {
    $('#dataTables-example').DataTable({
        responsive: true
    });
    $('[data-toggle="tooltip"]').tooltip();
});
</script>

Server/RailsServer/app/views/posts/index.html.erb
<div class="panel panel-default">
    <div class="panel-heading" align="center"><h2><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><br>Listing Donations</h2></div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Quantity(kg)</th>
                    <th>EXP Date</th>
                    <th>Avaliable Time</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @posts.each do |post| %>
                    <tr class="odd gradeX">
                        <td><%= link_to post.item, post, :class =>"btn btn-info btn-sm white-font survey-btn"%></td>
                        <td><%= post.quantity %></td>
                        <td><%= post.expir.to_formatted_s(:db) %></td>
                        <td>From: <%= post.available_time_start.to_formatted_s(:db) %> to: <%= post.available_time_end.to_formatted_s(:db) %></td>
                        <td>
                          <% if post.status == 0 %>
                            <%= link_to 'Edit', edit_post_path(post), :class =>"btn btn-warning btn-sm white-font survey-btn" %>
                            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure you want to delete this donate?' }, :class =>"btn btn-danger btn-sm white-font survey-btn" %>
                          <% else %>
                            Accpeted
                          <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
  <%= link_to 'New Donation', new_post_path, :class =>"btn btn-success btn-sm white-font" %>
    </div>
    <!-- /.panel-body -->
</div>
<script>
$(document).ready(function() {
    $('#dataTables-example').DataTable({
        responsive: true
    });
    $('[data-toggle="tooltip"]').tooltip();
});
</script>

Server/RailsServer/app/views/posts/new.html.erb
<div class="col-md-offset-3 col-md-6 col-md-offset-3"%>
  <div class="panel panel-default">
  <div class="panel-heading"><h2><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><br>New Donation</h2></div>
    <div class="panel-body">

		<%= render 'form' %>

   </div>
  </div>
  <%= link_to 'Back', posts_path, :class =>"btn btn-primary btn-sm white-font" %>
</div>

Server/RailsServer/app/views/posts/show.html.erb
<table class="table table-striped table-bordered table-hover" id="dataTables-example">
  <tbody>
    <tr>
      <th>Foods</th>
      <th><%= @post.item %></th>
    </tr>
    <tr>
      <th>Description</th>
      <th><%= @post.description %></th>
    </tr>
    <tr>
      <th>Quantity</th>
      <th><%= @post.quantity %> kg</th>
    </tr>
    <tr>
      <th>Location</th>
      <th><%= @post.loc %></th>
    </tr>
    <tr>
      <th>
        <label>Available from: </label>
        <%= @post.available_time_start %>
        <label>to: </label>
        <%= @post.available_time_end %>
      </th>
    </tr>
    <tr>
      <th>Expire date</th>
      <th><%= @post.expir %></th>
    </tr>
    <tr>
      <th>Picture</th>
      <th><img src=<%= @post.image.url %>></th>
    </tr>
</table>

Server/RailsServer/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div calss="field">
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :user_type %><br>
    <%= f.number_field :user_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Server/RailsServer/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Server/RailsServer/app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <%= form_for User.new, url: {action: "login"} ,html: {"role" => "form"} do |f| %>
                        <fieldset>
                            <div class="form-group">
                                <%= f.email_field :email, autofocus: true,class: "form-control", "placeholder" => "E-mail" %>
                            </div>
                            <div class="form-group">
                                <%= f.password_field :password, autocomplete: "off",class: "form-control", "placeholder" => "password"  %>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                </label>
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <%= f.submit "Login", class:"btn btn-lg btn-success btn-block"%>
                            <p align="center">Don't have an account?
                            <%= link_to 'Create a free account', new_user_path %>
                            </p>
                        </fieldset>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

Server/RailsServer/app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign Up</h3>
                </div>
                <div class="panel-body">
                    <%= form_for @user, html: {"role" =>"form"} do |f| %>
                        <% if @user.errors.any? %>
                            <div id="error_explanation">
                                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

                                <ul>
                                    <% @user.errors.full_messages.each do |message| %>
                                        <li><%= message %></li>
                                    <% end %>
                                </ul>
                            </div>
                        <% end %>
                        <fieldset>
                            <div class="form-group">
                                <%= f.email_field :email, autofocus: true,class: "form-control", "placeholder" => "E-mail" %>
                            </div>
                            <div class="form-group">
                                <%= f.text_field :name, class: "form-control", "placeholder" => "Name" %>
                            </div>
                            <div class="form-group">
                                <%= f.password_field :password, autocomplete: "off",class: "form-control", "placeholder" => "password"  %>
                            </div>
                            <div class="form-group">
                                <label>I'm a</label>
                                <%= f.select(:user_type,['Doner','Charity'], {}, {id: "userType",class: "form-control", "onchange" => "change_user_type()"}) %>
                            </div>
                            <div class="form-group" id="donerLocation" >
                                <%= f.text_field :location, class: "form-control", "placeholder" => "Store Location" %>
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <%= f.submit "Sign Up", class:"btn btn-lg btn-success btn-block"%>
                            <%= link_to 'Back', users_path %>
                        </fieldset>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

Server/RailsServer/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name%>

</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>User type:</strong>
  <%= @user.user_type %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>